### ISSUE TITLE
Lines are strange

### ISSUE THREAD

**Issue by SunR** [anubiann00b/QuickNote#15]
See screenshot :)

**Comment by SunR** [comment]
![screenshot_2015-06-08-23-20-48](https://cloud.githubusercontent.com/assets/9732008/8051798/ac6af2e4-0e35-11e5-8714-8b07671af83d.png)

**Comment by sylvia43** [comment]
What's strange about that?

**Comment by SunR** [comment]
Looks fine to me! :)

**Comment by sylvia43** [comment]
Coolio
